baseURL = 'https://blog.breath-alchemist.com/'
languageCode = 'en-us'
title = 'Breath Alchemist'
theme = 'mini'
googleAnalytics = 'G-9KDPBZY7T1'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = 'G-9KDPBZY7T1'
